---
- name: "copy backend folder"
  become: true
  synchronize:
    src: ../../backend
    dest: /home/ubuntu/
    recursive: true

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install node dependencies"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm i
- name: "build backend"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build
- name: "start backend"
  become: true
  shell: |
    cd /home/ubuntu/backend    
    pm2 start npm -- run start