- name: "install pre-reqs for Ansible."
  become: true
  apt:
    name: ["python3", "tar", "gzip", "nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Create APP Directory
  become_user: ubuntu
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Move backend files to remote server."
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

   
- name: Start PM2
  become_user: ubuntu
  become: yes
  shell: |
    cd /home/ubuntu/backend
    npm run build
    pm2 start npm --name backend -- start 
